name: Salesforce CI/CD with Docker CLI

on:
  push:
    branches:
      - Dev
      - QA
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Apex tests?"
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    env:
      TEST_FLAG: ${{ inputs.run_tests }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate based on branch
      - name: Set Environment Secrets
        if: github.ref == 'refs/heads/Dev'
        env:
          SFDX_URL: ${{ secrets.SFDX_URL }}
        run: |
          echo "Logging masked secret..."
          echo "First 10 chars: ${SFDX_URL:0:10}***"
          # Write to auth.txt for CLI login
          echo "${SFDX_URL}" > auth.txt
         # sf org login sfdx-url -f auth.txt -a DevOrg -s
        shell: bash
      - name: Verify auth.txt exists
        if: github.ref == 'refs/heads/Dev'
        run: |
          if [ -f auth.txt ]; then
            echo "auth.txt was created successfully!"
          else
            echo "auth.txt NOT found!"
            exit 1
          fi
        shell: bash
        
      - name: Inspect first few characters safely
        if: github.ref == 'refs/heads/Dev'
        run: |
          echo "First 10 characters of auth.txt (safe check):"
          head -c 10 auth.txt | od -c
        shell: bash
      
      - name: Login to Dev Org
        if: github.ref == 'refs/heads/Dev'
        run: sf org login sfdx-url -f auth.txt -a DevOrg -s
  
      - name: Set Environment Secrets
        if: github.ref == 'refs/heads/QA'
        env:
          SFDX_URL: ${{ secrets.SFDX_URL }}
        run: |
          echo "${SFDX_URL}" > auth.txt
          sf org login sfdx-url -f auth.txt -a QAOrg -s


      # Deploy with or without tests
      - name: Deploy to Salesforce
        run: |
          if [ "${TEST_FLAG}" = "true" ]; then
            echo "Running tests during deploy..."
            sf project deploy start -l RunLocalTests -w 60
          else
            echo "Deploying without tests..."
            sf project deploy start -l NoTestRun -w 60
          fi
