name: Salesforce CI/CD

on:
  push:
    branches:
      - dev
      - qa
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Apex tests?"
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TEST_FLAG: ${{ inputs.run_tests }}
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Use Salesforce CLI Docker Image
        run: |
          echo "Using Salesforce CLI from Docker"
        shell: bash

      - name: Setup SFDX inside container
        uses: actions/setup-node@v4 # enables commands
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      # Authenticate Based on Branch
      - name: Authenticate to Dev Org
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "${{ secrets.DEV_SFDX_URL }}" > devAuth.txt
          sf org login sfdx-url -f devAuth.txt -a DevOrg -s

      - name: Authenticate to QA Org
        if: github.ref == 'refs/heads/qa'
        run: |
          echo "${{ secrets.QA_SFDX_URL }}" > qaAuth.txt
          sf org login sfdx-url -f qaAuth.txt -a QaOrg -s

      # Deploy code based on branch
      - name: Deploy to Salesforce
        run: |
          if [ "${TEST_FLAG}" = "true" ]; then
            echo "Running tests before deployment..."
            sf project deploy start -l RunLocalTests -w 60
          else
            echo "Deploying without tests..."
            sf project deploy start -l NoTestRun -w 60
          fi
