name: Salesforce CI/CD with Docker CLI

on:
  push:
    branches:
      - Dev
      - QA
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Apex tests?"
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    env:
      TEST_FLAG: ${{ inputs.run_tests }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ===== Dev Branch Authentication =====
      - name: Authenticate Dev Org
        if: github.ref == 'refs/heads/Dev'
        env:
          SFDX_URL: ${{ secrets.DEV_SFDX_URL }}  # Dev repo secret
        run: |
          echo "Writing auth file for Dev Org..."
          echo "${SFDX_URL}" > auth.txt

          # Verify file creation
          if [ -f auth.txt ]; then
            echo "auth.txt created successfully!"
          else
            echo "auth.txt NOT found!"
            exit 1
          fi

          # Optional: inspect first few characters safely
          echo "First few characters (safe check):"
          head -c 10 auth.txt | od -c

          # Login to Dev Org
          sf org login sfdx-url -f auth.txt -a DevOrg -s
        shell: bash

      # ===== QA Branch Authentication =====
      - name: Authenticate QA Org
        if: github.ref == 'refs/heads/QA'
        env:
          SFDX_URL: ${{ secrets.QA_SFDX_URL }}  # QA repo secret
        run: |
          echo "Writing auth file for QA Org..."
          echo "${SFDX_URL}" > auth.txt

          # Verify file creation
          if [ -f auth.txt ]; then
            echo "auth.txt created successfully!"
          else
            echo "auth.txt NOT found!"
            exit 1
          fi

          # Optional: inspect first few characters safely
          echo "First few characters (safe check):"
          head -c 10 auth.txt | od -c

          # Login to QA Org
          sf org login sfdx-url -f auth.txt -a QAOrg -s
        shell: bash

      # ===== Deploy Salesforce Metadata =====
      - name: Deploy to Salesforce
        if: github.ref == 'refs/heads/Dev' || github.ref == 'refs/heads/QA'
        run: |
          if [ "${TEST_FLAG}" = "true" ]; then
            echo "Running tests during deployment..."
            sf project deploy start -l RunLocalTests -w 60
          else
            echo "Deploying without tests..."
            sf project deploy start -l NoTestRun -w 60
        shell: bash
