name: Delta Deployment to Dev (SGD enabled)

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Apex tests?"
        required: true
        type: boolean
        default: true

jobs:
  delta-deploy:
    runs-on: ubuntu-latest

    container:
      image: salesforce/cli:latest-full

    env:
      TEST_FLAG: ${{ inputs.run_tests }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install sfdx-git-delta plugin
        run: |
          echo "Installing sfdx-git-delta plugin..."
          echo y | sf plugins install sfdx-git-delta

      - name: Authenticate to Salesforce Dev Org
        env:
          SFDX_URL: ${{ secrets.DEV_SFDX_URL }}
        run: |
          echo "${SFDX_URL}" > auth.txt
          sf org login sfdx-url -f auth.txt -a DevOrg -s

      - name: Generate delta using sfdx-git-delta
        run: |
          git fetch origin main
          echo "Running sfdx-git-delta: from origin/main to HEAD"
          sf sgd:source:delta --from origin/main --to HEAD --output delta
          echo "Contents of delta directory:"
          ls -R delta

      - name: Exit if no delta package generated
        run: |
          if [ ! -f delta/package.xml ]; then
            echo "No changes to deploy or delta package not generated."
            exit 0
          fi

      - name: Deploy Delta Package to Dev Org
        run: |
          if [ "${TEST_FLAG}" = "true" ]; then
            echo "Deploying with tests..."
            sf project deploy start -x delta/package.xml -l RunLocalTests -w 60 --verbose
          else
            echo "Deploying without tests..."
            sf project deploy start -x delta/package.xml  -l NoTestRun -w 60 --verbose
          fi
