name: Delta Deployment to Dev

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Apex tests?"
        type: boolean
        default: true

jobs:
  delta-deploy:
    runs-on: ubuntu-latest

    container:
      image: salesforce/cli:latest-full

    env:
      TEST_FLAG: ${{ inputs.run_tests }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Salesforce
        env:
          SFDX_URL: ${{ secrets.DEV_SFDX_URL }}
        run: |
          echo "${SFDX_URL}" > auth.txt
          sf org login sfdx-url -f auth.txt -a DevOrg -s
        shell: bash

     
