name: Delta Deployment to Dev

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Apex tests?"
        type: boolean
        default: true

jobs:
  delta-deploy:
    runs-on: ubuntu-latest

    container:
      image: salesforce/cli:latest-full

    env:
      TEST_FLAG: ${{ inputs.run_tests }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Authenticate to Salesforce
        env:
          SFDX_URL: ${{ secrets.DEV_SFDX_URL }}
        run: |
          echo "${SFDX_URL}" > auth.txt
          sf org login sfdx-url -f auth.txt -a DevOrg -s
        shell: bash

      - name: Identify Changed Metadata
        run: |
          mkdir delta || true
          git fetch origin Dev
          changed_files=$(git diff --name-only origin/main...HEAD -- 'force-app/**' | tr '\n' ',' | sed 's/,$//')
          echo "Changed files for deployment: $changed_files"
          echo $changed_files > changed-files.txt
        shell: bash

      - name: Exit if nothing changed
        run: |
          if [ ! -s changed-files.txt ]; then
            echo "No metadata changes found. Skipping deployment."
            exit 0
          fi
        shell: bash

     
     # 4️⃣ Deploy only changed files
      - name: Deploy Delta Metadata
        run: |
          changed_files=$(cat changed-files.txt)
          if [ -z "$changed_files" ]; then
            echo "No changes to deploy."
            exit 0
          fi

          echo "Deploying changed metadata to DevOrg..."
          if [ "${TEST_FLAG}" = "true" ]; then
            sf project deploy start --source-dir $changed_files -u DevOrg -l RunLocalTests -w 60 --verbose
          else
            sf project deploy start --source-dir $changed_files -u DevOrg -l NoTestRun -w 60 --verbose
        shell: bash
