name: Delta Deployment to Dev

on:
  workflow_dispatch:   # Manual trigger for delta deployments

jobs:
  delta-deploy:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.DEV_SFDX_URL }}" > auth.txt
          sf org login sfdx-url -f auth.txt -a DevOrg -s
        shell: bash

      - name: Identify Changed Metadata
        run: |
          mkdir delta
          git fetch origin Dev
          git diff --name-only origin/Dev HEAD | grep "^force-app" > changed-files.txt || true
          echo "Changed Files:"
          cat changed-files.txt || echo "No metadata changed"
        shell: bash

      - name: Generate Delta Package.xml
        if: success()
        run: |
          if [ ! -s changed-files.txt ]; then
            echo "No metadata changes found. Exiting..."
            exit 0
          fi

          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > delta/package.xml
          echo "<Package xmlns=\"http://soap.sforce.com/2006/04/metadata\">" >> delta/package.xml

          while IFS= read -r file; do
            type=$(dirname "$file" | sed 's|force-app/main/default/||')
            name=$(basename "$file" | sed 's/\..*$//')

            echo "  <types>" >> delta/package.xml
            echo "    <members>${name}</members>" >> delta/package.xml
            echo "    <name>${type}</name>" >> delta/package.xml
            echo "  </types>" >> delta/package.xml
          done < changed-files.txt

          echo "  <version>60.0</version>" >> delta/package.xml
          echo "</Package>" >> delta/package.xml

          echo "Generated package.xml:"
          cat delta/package.xml
        shell: bash

      - name: Deploy Only Changed Metadata
        if: success()
        run: |
          if [ ! -s changed-files.txt ]; then
            echo "No deployment to run"
            exit 0
          fi

          echo "Deploying delta metadata to DevOrg..."
          sf project deploy start -x delta/package.xml -u DevOrg -l RunLocalTests -w 60 --verbose
        shell: bash
