name: Delta Deployment to Dev

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Apex tests?"
        type: boolean
        default: true

jobs:
  delta-deploy:
    runs-on: ubuntu-latest

    container:
      image: salesforce/cli:latest-full

    env:
      TEST_FLAG: ${{ inputs.run_tests }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Authenticate to Salesforce
        env:
          SFDX_URL: ${{ secrets.DEV_SFDX_URL }}
        run: |
          echo "${SFDX_URL}" > auth.txt
          sf org login sfdx-url -f auth.txt -a DevOrg -s

      - name: Identify Changed Metadata
        run: |
          git fetch origin main
          changed_files=$(git diff --name-only origin/main...HEAD -- 'force-app/**' | tr '\n' ',' | sed 's/,$//')
          echo "Changed files for deployment: $changed_files"
          echo "$changed_files" > changed-files.txt

      - name: Exit if nothing changed
        run: |
          if [ ! -s changed-files.txt ]; then
            echo "No metadata changes found. Skipping deployment."
            exit 0
          fi

      - name: Deploy Delta Metadata
        run: |
          changed_files=$(cat changed-files.txt)
          if [ -z "$changed_files" ]; then
            echo "No changes to deploy."
            exit 0
          fi
          
          deploy_args=""
          
          echo "Processing changed metadata:"
          for file in $changed_files; do
            if [[ "$file" == *"/lwc/"* ]]; then
              # LWC requires the whole component folder
              comp_folder=$(echo $file | sed 's|\(.*\/lwc\/[^\/]*\)\/.*|\1|')
              deploy_args+=" --source-dir $comp_folder"
            elif [[ "$file" == *"/aura/"* ]]; then
              comp_folder=$(echo $file | sed 's|\(.*\/aura\/[^\/]*\)\/.*|\1|')
              deploy_args+=" --source-dir $comp_folder"
            elif [[ "$file" == *.cls ]] || [[ "$file" == *.trigger ]] || [[ "$file" == *.xml ]]; then
              # Individual deployable files
              deploy_args+=" --source-dir $file"
            else
              # Default: deploy as folder
              parent_folder=$(dirname "$file")
              deploy_args+=" --source-dir $parent_folder"
            fi
          done
          
          echo "Deploying only changed metadata:"
          echo "$deploy_args"
          
          if [ "${TEST_FLAG}" = "true" ]; then
            sf project deploy start $deploy_args -l RunLocalTests -w 60 --verbose
          else
            sf project deploy start $deploy_args -l NoTestRun -w 60 --verbose
          fi

